# k8s-config/k8s/databases/postgres-admin-db-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-admin-db-deployment
spec:
  selector:
    matchLabels:
      app: postgres-admin-db
  template:
    metadata:
      labels:
        app: postgres-admin-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: admin_db
        - name: POSTGRES_USER
          value: admin_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin-secrets
              key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-admin-db-service
spec:
  type: ClusterIP
  selector:
    app: postgres-admin-db
  ports:
  - port: 5432
    targetPort: 5432
