apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: default
data:
  DB_HOST: "postgres-notification-db-service"
  DB_PORT: "5432"
  DB_NAME: "notification_db"
  DB_USER: "notification_user"
  SPRING_PROFILE: "dev"
  GRPC_PORT: "9090"
  EMAIL_ENABLED: "true"
