apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  DB_HOST: "postgres-payment-db-service"
  DB_PORT: "5432"
  DB_NAME: "payment_db"
  DB_USER: "payment_user"
  SPRING_PROFILE: "dev"
  # Inter-service URLs
  NOTIFICATION_SERVICE_URL: "http://notification-service:80"
  PAYHERE_MERCHANT_ID: "1231968"
  PAYHERE_SANDBOX: "true"
  PAYHERE_RETURN_URL: "https://techtorque.randitha.net/payment/success"
  PAYHERE_CANCEL_URL: "https://techtorque.randitha.net/payment/cancel"
  PAYHERE_NOTIFY_URL: "https://api.techtorque.randitha.net/api/payments/notify"
