apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
data:
  DB_HOST: "postgres-project-db-service"
  DB_PORT: "5432"
  DB_NAME: "project_db"
  DB_USER: "project_user"
  SPRING_PROFILE: "dev"
  # Inter-service URLs
  APPOINTMENT_SERVICE_URL: "http://appointment-service:80"
  NOTIFICATION_SERVICE_URL: "http://notification-service:80"
