apiVersion: v1
kind: ConfigMap
metadata:
  name: timelogging-config
  namespace: default
data:
  DB_HOST: "postgres-timelogging-db-service"
  DB_PORT: "5432"
  DB_NAME: "timelogging_db"
  DB_USER: "timelogging_user"
  SPRING_PROFILE: "dev"
