apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-config
  namespace: default
data:
  DB_HOST: "postgres-vehicle-db-service"
  DB_PORT: "5432"
  DB_NAME: "vehicle_db"
  DB_USER: "vehicle_user"
  SPRING_PROFILE: "dev"
