# k8s-config/k8s/services/admin-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service-container
        image: ghcr.io/techtorque-2025/admin_service:latest
        ports:
          - containerPort: 8087
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: admin-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: admin-config
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: admin-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: admin-config
                key: DB_USER
          - name: SPRING_PROFILE
            valueFrom:
              configMapKeyRef:
                name: admin-config
                key: SPRING_PROFILE
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: admin-secrets
                key: DB_PASS
          - name: AUTH_SERVICE_URL
            value: "http://auth-service:80"
          - name: VEHICLE_SERVICE_URL
            value: "http://vehicle-service:80"
          - name: APPOINTMENT_SERVICE_URL
            value: "http://appointment-service:80"
          - name: PROJECT_SERVICE_URL
            value: "http://project-service:80"
          - name: TIME_LOGGING_SERVICE_URL
            value: "http://time-logging-service:80"
          - name: PAYMENT_SERVICE_URL
            value: "http://payment-service:80"
          - name: NOTIFICATION_SERVICE_URL
            value: "http://notification-service:80"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: ClusterIP 
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8087
